language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
before_install:
- cp ci/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- cp ci/npm-config.sh $HOME/
- chmod +x $HOME/npm-config.sh
- $HOME/travis-ci.sh before-install
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
- cd built
after_deploy:
- $HOME/travis-ci.sh after-deploy
cache:
  directories:
  - node_modules
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalamuna.com
    - ben@kalamuna.com
    on_success: always
env:
  global:
  - secure: iKz8TBzkdX3tk1YXutCUuIFCn7B6FgrSVvAcsWHjJjDUKTG/RK2u58d4hUg4oSp1ub+qQDY/8ckjuNMziGPzZVL4ZGKRQCoK6Xm9AoyJ2IhNVPYpPHBEq6QJUZL6kSEOxHxa/Py54TVI6O0MwWgZoxk3idhnVBGBOakGqgO7hFs=
  - secure: gRckZ6HQOrmJ97c1R/pf4uqKJaT21GrMvP33N+B6yf9hUR8Zqd9rOGexgXTDGh9S8NpDX2TxVRTdiQIcRxXzOQq99vsqB6pfW4VebiVK5eKg9z7w+HdUi7dF2ixsVL/Co6rdIfrsACPVsHCe4bv+89L9T3B2iVfNFVdycop7Wdo=
  - secure: DSR6dlVQ3b/cfFoo0Z+y03nHJHfkhq0V/3OZlEI2t+evztAJwQ8IUO9JbP7aDsW4GUGtPysSB5LrMfOnHBF1PR8G4o1ZElIW3xEv6xx2X0iuvXlnekAgm2kEbn/q/NnmMsJJWTs7CwIWoXrlRpcPm+HjZjCw1CfEw4JJlBp1aQ4=
